Game server
COMP-413-Grey-Team/Basic-Repo pull request #10
Opened 2020-11-04 19:12 UTC by mja9

- Added maven to core subdirectory 
- Reconfigured proto executable to generate files outside of target
- Moved all necessary files to core to avoid working in basic-repo

2020-11-04 21:37 UTC, popatr15 requested changes
Code looks good but lets make sure to not push executables and config files besides the pom.xml to the repo.

2020-11-04 21:37 UTC, popatr15 commented on core/.idea/compiler.xml
> +  <component name="CompilerConfiguration">
Lets try not to push these .idea files to the main branch

2020-11-04 21:37 UTC, popatr15 commented on core/core.iml
> +<module org.jetbrains.idea.maven.project.MavenProjectsManager.isMavenModule="true" type="JAVA_MODULE" version="4">
Same thing here make sure we dont push this

2020-11-05 00:41 UTC, edekhayser approved these changes

2020-11-05 18:52 UTC, popatr15 approved these changes

2020-11-05 18:55 UTC, merged