Started updatePrimary and handleUpdate.
COMP-413-Grey-Team/Basic-Repo pull request #15
Opened 2020-11-09 01:50 UTC by vhellmer

There are a few questions that I had before we should merge:
- There seems to be an issue where it's giving me a warning that I can't call non-static ChangeReceiver.receiveChange in a static context. Since ChangeReceiver.receiveChange is under ObjStorage, I wasn't sure if that's an issue involving them?
- Should handleUpdate return a response? I didn't think it would, but wanted to confirm.
- In the case that updatePrimary is called from the server currently holding the primary, does it make sense to just call ChangeReciever and sendToReplicaHolders() in updatePrimary? - I can just case for that, but wasn't sure how we wanted to handle it.

2020-11-09 03:11 UTC, isabella-h requested changes

2020-11-09 03:11 UTC, isabella-h commented on core/src/edu/rice/rbox/Replication/ReplicaManagerGrpc.java
> +            ChangeReceiver.receiveChange(request.getRemoteChange());
Should do `changeReceiver.receiveChange` instead?

2020-11-09 03:11 UTC, isabella-h commented on core/src/edu/rice/rbox/Replication/ReplicaManagerGrpc.java
> +        // TODO: What if we're the primary?
This is handled by Object Storage, so it is only called when we're the replica holder

2020-11-09 03:11 UTC, isabella-h commented on core/src/edu/rice/rbox/Replication/ReplicaManagerGrpc.java
> +            ChangeReceiver.receiveChange(request.getRemoteChange());
And if we're updating the secondary, we should also notify the registrar about it.

2020-11-09 03:11 UTC, isabella-h commented on core/src/edu/rice/rbox/Replication/ReplicaManagerGrpc.java
> +            sendToReplicaHolders(request.getTargetObject(), request.getRemoteChange());
When we are handling update, we don't send to replica holders because the update might be rejected by object storage

2020-11-10 00:20 UTC, vhellmer commented
I believe I fixed the issues we talked about. I don't think there's a way to send messages with the registrar so far, but let me know if I'm mistaken. 

Otherwise, I know we talked about casing on it's a deleteReplicaChange in the update handler, but I'm not sure how to check that as the change seems to be just cast as a generic "RemoteChange" after getting it from the grpc message.

2020-11-10 05:43 UTC, isabella-h commented on core/src/edu/rice/rbox/Replication/ReplicaManagerGrpc.java
> +            // TODO: How do we check if change is DeleteReplicaChange?
Maybe research on whether serializing and deserializing would retain the subclass, would `if (change instanceof DeleteReplicaChange)` work?

2020-11-11 22:40 UTC, merged